### ISSUE TITLE
或可添加`recipe.yaml`，从而能够通过`plum`安装词库

### ISSUE THREAD

**Issue by DeepChirp** [outloudvi/mw2fcitx#31]
我认为可以在仓库中添加`recipe.yaml`，方便使用`plum`的用户安装此词库。

参考自`fcitx5-pinyin-zhwiki`仓库：
```yaml
# encoding: utf-8
---
recipe:
  Rx: moegirl-dict
  description: >-
    Install moegirl dict from fcitx5-pinyin-moegirl
download_files: >-
  moegirl.dict.yaml::https://github.com/outloudvi/mw2fcitx/releases/download/20241211/moegirl.dict.yaml
install_files: >-
  moegirl.dict.yaml
```

然后用户使用下列命令应该就能够安装词库：
```bash
rime-install outloudvi/mw2fcitx
```
